apiVersion: v1
kind: Pod
metadata:
  name: serverlessgo
spec:
  containers:
  - name: router
    image: gcr.io/k8stest-167418/serverlessgo:2.0.0
    command: ["/var/runtime/serverlessgo"]
    ports:
    - containerPort: 28903
    volumeMounts:
    - name: functions
      mountPath: /var/runtime/func
  volumes:
  - name: functions
    hostPath:
      path: /functions
    