apiVersion: batch/v1
kind: Job
metadata:
  name: smalljob
spec:
  template:
    metadata:
      name: smalljob
    spec:
      containers:
      - name: smalljob
        image: busybox
        command:
         - "bin/bash"
         - "-c"
         - "for i in 9 8 7 6 5 4 3 2 1 ; do echo $i ; done"
      restartPolicy: Never