apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: gofunc1
spec:
  template:
    metadata:
      labels:
        run-once-daemonset: gofunc1
    spec:
      containers:
      - name: gofunc1
        image: gcr.io/k8stest-167418/gofunc1:1.0.0
        command: ["/bin/sh"]
        args: ["-c","mkdir /var/runtime/func/gofunc1:1.0.0; cp -fr /code/* /var/runtime/func/gofunc1:1.0.0/.;  tail -f /dev/null"]  
        imagePullPolicy: Always
        volumeMounts:
        - name: functions
          mountPath: /var/runtime/func
      volumes:
      - name: functions
        hostPath:
          path: /functions